version: '3.9'

services:
  db:
    container_name: NTTDATA-Webapp-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: wpdatabase 
    ports:
      - 33066:3306
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./docker-database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  phpmyadmin:
    container_name: NTTDATA-Webapp-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wordpress:
    container_name: NTTDATA-Webapp-wordpress
    depends_on:
      - db
    image: wordpress:6.3.0-php8.2
    ports:
      - 3001:80
    volumes:
      - ./src:/var/www/html/
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 
      WORDPRESS_DB_NAME: wpdatabase
      WORDPRESS_DB_NAME_DOCKER: wpdatabase
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
    mysql:
    src: